### PR TITLE
Fix None float value

### PR DESCRIPTION
**Pull request by Farkal**
I added a test file, but i think we can create on big file with all type of fields and test each of them.
To check if value was `None` i just check all char was equal to `*`. I think the same can be apply to Numeric and Double but perhaps it's linked with the lib encoding the value 😕

### CODE REVIEW

**Comment by tmontaigu** [comment]
Strange that "*" is used a a character to indicated null value I've only read that space where used for that, what did you use to create this file ?

**Comment by Farkal** [comment]
The script i put in the issue #2:

You will need to have python 3.6 and run `pip install pyshp`

```
import shapefile

writer = shapefile.Writer(shapefile.POLYGON)

writer.autoBalancer = 1

writer.field('name','C')
writer.field('money','F')

prop = {
    "name": 'myname',
    "money": None,
}

coords = [(0,0), (0,1), (1,1), (0,1), (0,0)]

writer.poly(parts=[coords])

values = list(prop.values())

writer.record(*values)

writer.save('test.shp')
```

**Comment by tmontaigu** [comment]
Ok, I created the file with the script but forgot to test the crate on it 🤔 .

I looked at the [pyshp code](https://github.com/GeospatialPython/pyshp/blob/71231ddc5aa54f155d4f0563c56006fffbfc84e7/shapefile.py#L938) and the same thing should be done for the `FieldValue::Numeric`

**Comment by Farkal** [comment]
I added the check and add other field types to the test. It should be ok now 😉

**Comment by tmontaigu** [comment]
Thanks

**Pull request merged**
